= 01: Where are function local variables stored?
Daniel Langr <daniel.langr@gmail.com>
//:revdate: {docdate}
:revdate: March 2021
//:revremark: last modification
:rootdir: ..
include::{rootdir}/include/attributes.adoc[]
:description: A program needs to provide only the observable behavior prescribed to its source code.

[.normal]
//link:../index.html[Homepage]
xref:../index.adoc#_contents[Table of contents]

''''

****
*“Where are function local variables stored?”*
****

What is wrong with this question? And, what is wrong with the answer *“On the stack.”*? Actually, almost everything. Even if we rewrite the question to a bit more exact form:

****
*“Where are function local variables with automatic storage duration stored when the function is executed at runtime?”*
****

the things won't go any better. Why? First, *there are no variables at runtime*. A variable is an *abstraction mechanism* that exist only *at the source code level*. Basically, a variable is a *named instance of some data type*. But *CPUs do not refer memory by names* and *memory does not recognize data types*. We should better speak about *variable values being stored in memory* than variables themselves. This may not sound like a big deal, but there come more serious ones.

{cpp} itself -- defined by the {cpp} standard -- *doesn't have the concept of stack*. From the perspective of {cpp}, values of function local variables *cannot be stored at a place it does not recognize*. Yet, all today's mainstream CPU architectures are stack-based and {cpp} implementations reflect it. Can we say at least that *on a typical modern computer system, values of function local variables are stored on the stack*? No, even this is *generally wrong*. Consider the following function:

[source]
----
void f()
{
  int a = 1;
  int b = 2;
  int c = a + b;
}
----

When I compiled it with GCC on an x86_64 system, I obtained the following (disassembled) machine code:

[source,x86asm]
----
f():
  ret
----

We can clearly see that the values of `a`,`b`, and `c` variables *do not at all exist at runtime*. Not only they are *not stored on the stack*, they are even not stored anywhere else. Generally, variable values *may be stored on the stack*, but this was not the case.

I was even able to involve *more complex (non-trivial class) data type*:

[source]
----
class Int
{
  int i_;
public:
  Int(int i) : i_(i) { }
  operator int&() { return i_; }
};

void f()
{
  Int a = 1;
  Int b = 2;
  Int c = a + b;
}
----

with the *very same outcome*:

[source,x86asm]
----
f():
  ret
----

To understand what happened here we need to get familiar with some of the key {cpp} mechanisms -- *the as-if rule and the observable behavior concept*. We will get to them later in this tutorial.

include::{rootdir}/include/disqus.adoc[]
include::{rootdir}/include/copyright.adoc[]
