= 03: Programming and abstractions II
Daniel Langr <daniel.langr@gmail.com>
//:revdate: {docdate}
:revdate: March 2021
//:revremark: last modification
:rootdir: ..
include::{rootdir}/include/attributes.adoc[]
//:description: A program needs to provide only the observable behavior prescribed to its source code.

[.normal]
//link:../index.html[Homepage]
xref:../index.adoc#_contents[Table of contents]

''''

*Different programming languages* provide *differnt sets of abstraction mechanisms*. Accordingly, we can generally classify programming laguages into low-level programming languages and high-level programming languages. *Low-level programming languages* provide *simple (“closer-to-hardware”) abstraction mechanisms*, such as pointers. *High-level programming languages* provide *more complex and sophisticated (“closer-to-our-thinking”) abstraction mechanisms*, such as polymorphism. The latter ones allow us to express some functionality more easily.

*But there is a price.* Generally, it does hold that *higher abstraction comes with lower system control*, that is, the control of what the CPU coes, how the program works with memory, and how it interascts with the operting system. A general rule of thumb is that programming with *lower-level languages* requires *more effort* but allows *better system control*, and vice versa.

Let us look at some particular programming languages in this perspcetive. The lowest-level programming language is *assembler*. With assembler, we have a *total control* over a computer system since there is one-to-one correspondence between the assembler instructions and the machine code instructions (opcodes). However, programming in assembler has two major drawbacks -- first, it takes a *tremendous amount of effort* to express some functionlaity in it, and, second, the written source code is generally *not portable*.

A bit higher-level programming language is *C*. In contrast to assembler, source code written in C is *portable*. But still, the *amount of effort* to express some functionality in C is *large to moderate*. With C, we have a *good system control* due to low-level abstraction mechanisms such as pointers, alignment handling, atomics, memory model specifications, dynamic memory allocations, etc.

At the opposite side of the _level-of-abstraction / system-control_ scale would be likely the today's most popular programming languge -- *Python*. It is *easy to learn*, and it is *easy to express some functionality* with its source code. But it provides *very little control* about what happens in the system when this funtionality is performed. For example, we have no pointers in Python, and without pointers, we cannot control memory. Or, we have no atomics, and without atomics, we cannot control and fine-tune inter-thread communication and synchronization.

So, finally, *what about {cpp}*? We will look at it in the very next post.

include::{rootdir}/include/disqus.adoc[]
include::{rootdir}/include/copyright.adoc[]
